import argparse
from wandb_train import main

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset_name", type=str, default="yousician_aegiskc")
    parser.add_argument("--model_name", type=str, default="aegiskc")
    parser.add_argument("--emb_type", type=str, default="aegiskc")
    parser.add_argument("--save_dir", type=str, default="saved_model/aegiskc")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--fold", type=int, default=0)
    parser.add_argument("--dropout", type=float, default=0.1)
    parser.add_argument("--emb_size", type=int, default=200)
    parser.add_argument("--hidden_size", type=int, default=-1)
    parser.add_argument("--attn_dim", type=int, default=-1)
    parser.add_argument("--learning_rate", type=float, default=1e-3)
    parser.add_argument("--aegiskc_item_fields", type=str, default="")
    parser.add_argument("--qid_residual", action="store_true")
    parser.add_argument("--qid_residual_scale", type=float, default=0.1)
    parser.add_argument("--batch_size", type=int, default=256)
    parser.add_argument("--num_epochs", type=int, default=200)
    parser.add_argument("--use_wandb", type=int, default=1)
    parser.add_argument("--add_uuid", type=int, default=1)
    args = parser.parse_args()
    main(vars(args))
